### ISSUE TITLE
z-index

### ISSUE THREAD

**Issue by Markmcl** [anandkumar/jquery-smooth-scroll#10]
could you add `.a#scroll-to-top{
    z-index: 11;
}`
if you do an update? the arrow slides below my footer and child theme does not seem to be able to get it to work. I hacked the plugin to fix it, but that won't last past any update. Thanks for the plugin.

**Comment by anandkumar** [comment]
Add the CSS in your child theme file and use `!important` to enforce it. It will sustain forever. ;)

Adding such code will possibly break others.
