### ISSUE TITLE
How do I remove the scroll up button?

### ISSUE THREAD

**Issue by MajorErection** [anandkumar/jquery-smooth-scroll#9]
As the title states, I only want the smooth scroll to anchor links function. Without the scroll up button

**Comment by anandkumar** [comment]
The easiest way to do that is commenting out the following line:
 https://github.com/anandkumar/jquery-smooth-scroll/blob/ea69dd17d2bae7fbc085d63fa8431d5b5891ccb5/jquery-smooth-scroll.php#L60
